# Generated by Django 2.0.7 on 2018-08-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='editora',
            name='livro',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='livro',
        ),
    ]
